# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171026_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='organization/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
