# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-24 17:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20171124_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
    ]
