# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u7ae0\u8282\u65f6\u957f\uff08\u5206\u949f\uff09'),
        ),
    ]
